name: Build and Release VSIX

on:
  push:
    branches:
      - main  # oder der Name Ihres Hauptbranches

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y.%m.%d.%H%M')"
      shell: bash

    - name: Restore NuGet packages
      run: nuget restore CleanerAnalyzer2\CleanerAnalyzer2.sln

    - name: Build VSIX
      run: msbuild CleanerAnalyzer2\CleanerAnalyzer2.sln /p:Configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

    - name: Publish NuGet package
      run: dotnet nuget push .\CleanerAnalyzer2\CleanerAnalyzer2\CleanerAnalyzer2.Package\bin\Release\*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
